### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by alexarje** [balintlaczko/MGT-python#27]
When trying to run the two examples under /examples, I get the following error: 

> Traceback (most recent call last):
  File "test_dance.py", line 9, in <module>
    from _average import average_image
  File "../mgmodule/_average.py", line 4, in <module>
    from ._utils import mg_progressbar, MgImage
ImportError: attempted relative import with no known parent package

Guess they need updating to paths

**Comment by balintlaczko** [comment]
Yes, I haven't updated those yet, but will soon!
