### ISSUE TITLE
Add audio to exported videos

### ISSUE THREAD

**Issue by alexarje** [balintlaczko/MGT-python#31]
I often use this one-liner to copy audio from one video to another: 

    ffmpeg -i input1.mp4 -i input2.avi -c copy -map 1:v:0 -map 0:a:0 -shortest out.avi

And if you also want to convert it to MP4, this will force conversion using .h264 and aac audio: 

    ffmpeg -i dance.avi -i dance_motion.avi -c copy -map 1:v:0 -map 0:a:0 -shortest -c:v mpeg4 -c:a aac dance_motion_audio.mp4

The latter may be best to give end-users a final video.

**Comment by balintlaczko** [comment]
Just learned how to timestretch/shrink audio with ffmpeg, which means we can have audio even for files in which we are skipping frames. Yaay!

**Comment by balintlaczko** [comment]
implemented audio in processing stage: https://github.com/balintlaczko/MGT-python/commit/1abf7ac49afd0bff0ea46961cb8485f1566745ca
