### ISSUE TITLE
Description of threshold in notebook

### ISSUE THREAD

**Issue by alexarje** [balintlaczko/MGT-python#32]
Would be good to add a section in the notebook explaining how thresholding of the motion video influences the result.

**Comment by alexarje** [comment]
I have made a filtering example here: https://github.com/fourMs/MGT-python/blob/master/examples/Filtering.ipynb

Made it as a separate notebook since I don't have access to Balint's repo, and didn't want to mess up something with the merge back. But it is probably good to include the threshold examples as part of the introduction notebook.

**Comment by balintlaczko** [comment]
OK, moving them in there!
