### ISSUE TITLE
All sub-modules should work with absolute paths as well

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/MGT-python#6]
As of now the source video file has to be in the same folder from where the call the mg.functions (and where we create an MgObject). Would be nice if it could work with any path passed.

**Comment by alenaclim** [comment]
I can work on fixing this!

**Comment by balintlaczko** [comment]
The paths are actually fine, the problem was (is) with the codec, closing this, and opening separate issue

**Comment by alenaclim** [comment]
This was not the actual problem, indeed, but the codec. I'll close this and open another one'
